# Generated by Django 5.0.7 on 2024-08-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Naivasha', 'Naivasha'), ('Mombasa', 'Mombasa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='levelofstudy',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='position',
            field=models.CharField(choices=[('SingleOrphan', 'SingleOrphan'), ('DoubleOrphan', 'DoubleOrphan'), ('Disabled', 'Disabled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contunuing', 'Contunuing'), ('Discontinued', 'Discontinued'), ('Completed', 'Completed')], max_length=30),
        ),
    ]
