# Generated by Django 5.0.7 on 2024-07-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_dataentry', models.BooleanField(default=False)),
                ('is_finance', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
