# Generated by Django 5.0.7 on 2024-08-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0002_alter_donor_gender_alter_school_location_and_more'),
        ('smsApp', '0002_smsappaccount'),
    ]

    operations = [
    ]
